# ----------------------------------------------------------------------------------------------------------------------
# Copyright (c) 2025, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.

FROM scratch

COPY runner /files/runner

EXPOSE 8080

ENTRYPOINT ["/files/runner"]
CMD ["-h"]
