//
// Copyright (c) 2020, 2023 Oracle and/or its affiliates.
//
// Licensed under the Universal Permissive License v 1.0 as shown at
// https://oss.oracle.com/licenses/upl.

// Authors:
//  Mahesh Kannan
//  Jonathan Knight

// NamedCacheService message types
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.2
// source: messages.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An enum representing the request type
type MapListenerRequest_RequestType int32

const (
	// The request to initialise the channel.
	MapListenerRequest_INIT MapListenerRequest_RequestType = 0
	// The request is for a key listener.
	MapListenerRequest_KEY MapListenerRequest_RequestType = 1
	// The request is for a Filter listener.
	MapListenerRequest_FILTER MapListenerRequest_RequestType = 2
)

// Enum value maps for MapListenerRequest_RequestType.
var (
	MapListenerRequest_RequestType_name = map[int32]string{
		0: "INIT",
		1: "KEY",
		2: "FILTER",
	}
	MapListenerRequest_RequestType_value = map[string]int32{
		"INIT":   0,
		"KEY":    1,
		"FILTER": 2,
	}
)

func (x MapListenerRequest_RequestType) Enum() *MapListenerRequest_RequestType {
	p := new(MapListenerRequest_RequestType)
	*p = x
	return p
}

func (x MapListenerRequest_RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MapListenerRequest_RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (MapListenerRequest_RequestType) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x MapListenerRequest_RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MapListenerRequest_RequestType.Descriptor instead.
func (MapListenerRequest_RequestType) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{30, 0}
}

// An enum of TransformationState values to describes how a CacheEvent has been or should be transformed.
type MapEventResponse_TransformationState int32

const (
	// Value used to indicate that an event is non-transformable and should
	// not be passed to any transformer-based listeners.
	MapEventResponse_NON_TRANSFORMABLE MapEventResponse_TransformationState = 0
	// Value used to indicate that an event is transformable and could be
	// passed to transformer-based listeners.
	MapEventResponse_TRANSFORMABLE MapEventResponse_TransformationState = 1
	// Value used to indicate that an event has been transformed, and should
	// only be passed to transformer-based listeners.
	MapEventResponse_TRANSFORMED MapEventResponse_TransformationState = 2
)

// Enum value maps for MapEventResponse_TransformationState.
var (
	MapEventResponse_TransformationState_name = map[int32]string{
		0: "NON_TRANSFORMABLE",
		1: "TRANSFORMABLE",
		2: "TRANSFORMED",
	}
	MapEventResponse_TransformationState_value = map[string]int32{
		"NON_TRANSFORMABLE": 0,
		"TRANSFORMABLE":     1,
		"TRANSFORMED":       2,
	}
)

func (x MapEventResponse_TransformationState) Enum() *MapEventResponse_TransformationState {
	p := new(MapEventResponse_TransformationState)
	*p = x
	return p
}

func (x MapEventResponse_TransformationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MapEventResponse_TransformationState) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[1].Descriptor()
}

func (MapEventResponse_TransformationState) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[1]
}

func (x MapEventResponse_TransformationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MapEventResponse_TransformationState.Descriptor instead.
func (MapEventResponse_TransformationState) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{37, 0}
}

// A request to clear all the entries in the cache.
type ClearRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache         string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearRequest) Reset() {
	*x = ClearRequest{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearRequest) ProtoMessage() {}

func (x *ClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearRequest.ProtoReflect.Descriptor instead.
func (*ClearRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ClearRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ClearRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

// A request to determine whether an entry exists in a cache
// with a specific key and value.
type ContainsEntryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	// The serialization format.
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// The serialization format.
	Key []byte `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	// The value of the entry to verify.
	Value         []byte `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainsEntryRequest) Reset() {
	*x = ContainsEntryRequest{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainsEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainsEntryRequest) ProtoMessage() {}

func (x *ContainsEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainsEntryRequest.ProtoReflect.Descriptor instead.
func (*ContainsEntryRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ContainsEntryRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ContainsEntryRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *ContainsEntryRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ContainsEntryRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ContainsEntryRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// A request to determine whether an entry exists in a cache
// for the specified key.
type ContainsKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	// The serialization format.
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// The key of the entry to verify.
	Key           []byte `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainsKeyRequest) Reset() {
	*x = ContainsKeyRequest{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainsKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainsKeyRequest) ProtoMessage() {}

func (x *ContainsKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainsKeyRequest.ProtoReflect.Descriptor instead.
func (*ContainsKeyRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ContainsKeyRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ContainsKeyRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *ContainsKeyRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ContainsKeyRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

// A request to determine whether an entry exists in a cache
// with the specified value.
type ContainsValueRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	// The serialization format.
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// The value of the entry to verify.
	Value         []byte `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainsValueRequest) Reset() {
	*x = ContainsValueRequest{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainsValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainsValueRequest) ProtoMessage() {}

func (x *ContainsValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainsValueRequest.ProtoReflect.Descriptor instead.
func (*ContainsValueRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *ContainsValueRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ContainsValueRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *ContainsValueRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ContainsValueRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// A request to destroy a cache.
type DestroyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache         string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRequest) Reset() {
	*x = DestroyRequest{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRequest) ProtoMessage() {}

func (x *DestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRequest.ProtoReflect.Descriptor instead.
func (*DestroyRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *DestroyRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *DestroyRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

// A request to determine whether a cache is empty or not.
type IsEmptyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache         string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsEmptyRequest) Reset() {
	*x = IsEmptyRequest{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsEmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsEmptyRequest) ProtoMessage() {}

func (x *IsEmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsEmptyRequest.ProtoReflect.Descriptor instead.
func (*IsEmptyRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *IsEmptyRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *IsEmptyRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

// A request to check the ready status of a cache.
// @since 14.1.1.2206.5
type IsReadyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache         string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsReadyRequest) Reset() {
	*x = IsReadyRequest{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsReadyRequest) ProtoMessage() {}

func (x *IsReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsReadyRequest.ProtoReflect.Descriptor instead.
func (*IsReadyRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *IsReadyRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *IsReadyRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

// A request to determine the number of entries in a cache.
type SizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache         string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SizeRequest) Reset() {
	*x = SizeRequest{}
	mi := &file_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeRequest) ProtoMessage() {}

func (x *SizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeRequest.ProtoReflect.Descriptor instead.
func (*SizeRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *SizeRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *SizeRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

// A request to obtain the value to which a cache maps the
// specified key.
type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	// The serialization format.
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// The key of the entry to retrieve.
	Key           []byte `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *GetRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *GetRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *GetRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

// A request to obtain the values that map to the specified keys
type GetAllRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	// The serialization format.
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// The key of the entry to retrieve.
	Key           [][]byte `protobuf:"bytes,4,rep,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *GetAllRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *GetAllRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *GetAllRequest) GetKey() [][]byte {
	if x != nil {
		return x.Key
	}
	return nil
}

// A request to associate the specified value with the
// specified key in a cache.
type PutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	// The serialization format.
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// The cache entry key.
	Key []byte `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	// The value of the entry.
	Value []byte `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	// The time to live in millis.
	Ttl           int64 `protobuf:"varint,6,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *PutRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *PutRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *PutRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

// A request to associate the specified value with the
// specified key in a cache.
type PutAllRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	// The serialization format.
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// The cache entries to put.
	Entry []*Entry `protobuf:"bytes,4,rep,name=entry,proto3" json:"entry,omitempty"`
	// The time to live in millis.
	Ttl           int64 `protobuf:"varint,6,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutAllRequest) Reset() {
	*x = PutAllRequest{}
	mi := &file_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAllRequest) ProtoMessage() {}

func (x *PutAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAllRequest.ProtoReflect.Descriptor instead.
func (*PutAllRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11}
}

func (x *PutAllRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *PutAllRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *PutAllRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *PutAllRequest) GetEntry() []*Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *PutAllRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

// A request to associate the specified value with the
// specified key in a cache only if the specified key
// is not associated with any value (including null).
type PutIfAbsentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	// The serialization format.
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// The cache entry key.
	Key []byte `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	// The value to be put.
	Value []byte `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	// The time to live in millis.
	Ttl           int64 `protobuf:"varint,6,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutIfAbsentRequest) Reset() {
	*x = PutIfAbsentRequest{}
	mi := &file_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutIfAbsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutIfAbsentRequest) ProtoMessage() {}

func (x *PutIfAbsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutIfAbsentRequest.ProtoReflect.Descriptor instead.
func (*PutIfAbsentRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{12}
}

func (x *PutIfAbsentRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *PutIfAbsentRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *PutIfAbsentRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *PutIfAbsentRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutIfAbsentRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutIfAbsentRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

// A request to remove the mapping for a key from a cache
// if it is present.
type RemoveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	// The serialization format.
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// The key of the entry to be removed.
	Key           []byte `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *RemoveRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *RemoveRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *RemoveRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

// A request to remove the mapping for a key from a cache
// only if the specified key is associated with the specified
// value in that cache.
type RemoveMappingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	// The serialization format.
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// The key of the entry to be removed.
	Key []byte `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	// The value of the entry to verify.
	Value         []byte `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMappingRequest) Reset() {
	*x = RemoveMappingRequest{}
	mi := &file_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMappingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMappingRequest) ProtoMessage() {}

func (x *RemoveMappingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMappingRequest.ProtoReflect.Descriptor instead.
func (*RemoveMappingRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveMappingRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *RemoveMappingRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *RemoveMappingRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *RemoveMappingRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RemoveMappingRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// A request to replace the mapping for the specified key
// with the specified value in a cache only if the specified
// key is associated with some value in that cache.
type ReplaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	// The serialization format.
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// The key of the entry to be replaced.
	Key []byte `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	// The value of the entry to be replaced.
	Value         []byte `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceRequest) Reset() {
	*x = ReplaceRequest{}
	mi := &file_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceRequest) ProtoMessage() {}

func (x *ReplaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceRequest.ProtoReflect.Descriptor instead.
func (*ReplaceRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{15}
}

func (x *ReplaceRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ReplaceRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *ReplaceRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ReplaceRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ReplaceRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// A request to replace the mapping for the specified key
// with the specified newValue in a cache only if the specified
// key is associated with the specified previousValue in
// that cache.
type ReplaceMappingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	// The serialization format.
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// The key of the entry to be replaced.
	Key []byte `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	// The previous value that should exist in the cache.
	PreviousValue []byte `protobuf:"bytes,5,opt,name=previousValue,proto3" json:"previousValue,omitempty"`
	// The new value to put.
	NewValue      []byte `protobuf:"bytes,6,opt,name=newValue,proto3" json:"newValue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceMappingRequest) Reset() {
	*x = ReplaceMappingRequest{}
	mi := &file_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceMappingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceMappingRequest) ProtoMessage() {}

func (x *ReplaceMappingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceMappingRequest.ProtoReflect.Descriptor instead.
func (*ReplaceMappingRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{16}
}

func (x *ReplaceMappingRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ReplaceMappingRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *ReplaceMappingRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ReplaceMappingRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ReplaceMappingRequest) GetPreviousValue() []byte {
	if x != nil {
		return x.PreviousValue
	}
	return nil
}

func (x *ReplaceMappingRequest) GetNewValue() []byte {
	if x != nil {
		return x.NewValue
	}
	return nil
}

// A request for a page of data from a cache.
// This request is used for implementing methods such as NamedCache.keySet(),
// NamedCache.entrySet() and NamedCache.values() where it would be impractical
// to return the whole data set in one response.
type PageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	// The serialization format
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// An opaque cookie to track the requested page.
	Cookie        []byte `protobuf:"bytes,4,opt,name=cookie,proto3" json:"cookie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{17}
}

func (x *PageRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *PageRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *PageRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *PageRequest) GetCookie() []byte {
	if x != nil {
		return x.Cookie
	}
	return nil
}

// A cache entry key/value pair.
type EntryResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The cache entry key.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The cache entry value.
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// An opaque cookie to track the requested page.
	Cookie        []byte `protobuf:"bytes,3,opt,name=cookie,proto3" json:"cookie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryResult) Reset() {
	*x = EntryResult{}
	mi := &file_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryResult) ProtoMessage() {}

func (x *EntryResult) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryResult.ProtoReflect.Descriptor instead.
func (*EntryResult) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{18}
}

func (x *EntryResult) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *EntryResult) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *EntryResult) GetCookie() []byte {
	if x != nil {
		return x.Cookie
	}
	return nil
}

// A key value pair.
type Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The cache entry key.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The value of the entry.
	Value         []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{19}
}

func (x *Entry) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Entry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// A request to truncate a cache.
type TruncateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache         string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TruncateRequest) Reset() {
	*x = TruncateRequest{}
	mi := &file_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TruncateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruncateRequest) ProtoMessage() {}

func (x *TruncateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruncateRequest.ProtoReflect.Descriptor instead.
func (*TruncateRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{20}
}

func (x *TruncateRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *TruncateRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

// A request to add an index to a cache
type AddIndexRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	// The serialization format.
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// The serialized ValueExtractor to use to create the index.
	Extractor []byte `protobuf:"bytes,4,opt,name=extractor,proto3" json:"extractor,omitempty"`
	// A flag indicating whether to sort the index.
	Sorted bool `protobuf:"varint,5,opt,name=sorted,proto3" json:"sorted,omitempty"`
	// The optional comparator to use to sort the index.
	Comparator    []byte `protobuf:"bytes,6,opt,name=comparator,proto3" json:"comparator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddIndexRequest) Reset() {
	*x = AddIndexRequest{}
	mi := &file_messages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddIndexRequest) ProtoMessage() {}

func (x *AddIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddIndexRequest.ProtoReflect.Descriptor instead.
func (*AddIndexRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{21}
}

func (x *AddIndexRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *AddIndexRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *AddIndexRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *AddIndexRequest) GetExtractor() []byte {
	if x != nil {
		return x.Extractor
	}
	return nil
}

func (x *AddIndexRequest) GetSorted() bool {
	if x != nil {
		return x.Sorted
	}
	return false
}

func (x *AddIndexRequest) GetComparator() []byte {
	if x != nil {
		return x.Comparator
	}
	return nil
}

// A request to remove an index from a cache
type RemoveIndexRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	// The serialization format.
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// The serialized ValueExtractor to use to create the index.
	Extractor     []byte `protobuf:"bytes,4,opt,name=extractor,proto3" json:"extractor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveIndexRequest) Reset() {
	*x = RemoveIndexRequest{}
	mi := &file_messages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveIndexRequest) ProtoMessage() {}

func (x *RemoveIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveIndexRequest.ProtoReflect.Descriptor instead.
func (*RemoveIndexRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{22}
}

func (x *RemoveIndexRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *RemoveIndexRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *RemoveIndexRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *RemoveIndexRequest) GetExtractor() []byte {
	if x != nil {
		return x.Extractor
	}
	return nil
}

// A request to aggreagte entries in a cache.
type AggregateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	// The serialization format.
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// The serialized EntryAggregator to aggregate.
	Aggregator []byte `protobuf:"bytes,4,opt,name=aggregator,proto3" json:"aggregator,omitempty"`
	// The optional set of serialized keys of the entries to aggregate.
	Keys [][]byte `protobuf:"bytes,5,rep,name=keys,proto3" json:"keys,omitempty"`
	// The optional serialized Filter to identify the entries to aggregate.
	Filter        []byte `protobuf:"bytes,6,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateRequest) Reset() {
	*x = AggregateRequest{}
	mi := &file_messages_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateRequest) ProtoMessage() {}

func (x *AggregateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateRequest.ProtoReflect.Descriptor instead.
func (*AggregateRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{23}
}

func (x *AggregateRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *AggregateRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *AggregateRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *AggregateRequest) GetAggregator() []byte {
	if x != nil {
		return x.Aggregator
	}
	return nil
}

func (x *AggregateRequest) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *AggregateRequest) GetFilter() []byte {
	if x != nil {
		return x.Filter
	}
	return nil
}

// A request to invoke an EntryProcessor against a single entry.
type InvokeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	// The serialization format.
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// The serialized EntryProcessor to invoke.
	Processor []byte `protobuf:"bytes,4,opt,name=processor,proto3" json:"processor,omitempty"`
	// The serialized key of the entry to process.
	Key           []byte `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_messages_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{24}
}

func (x *InvokeRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *InvokeRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *InvokeRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *InvokeRequest) GetProcessor() []byte {
	if x != nil {
		return x.Processor
	}
	return nil
}

func (x *InvokeRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

// A request to invoke an entry processor against a number of entries.
type InvokeAllRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	// The serialization format.
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// The serialized EntryProcessor to invoke.
	Processor []byte `protobuf:"bytes,4,opt,name=processor,proto3" json:"processor,omitempty"`
	// The optional set of serialized keys of the entries to process.
	Keys [][]byte `protobuf:"bytes,5,rep,name=keys,proto3" json:"keys,omitempty"`
	// The optional serialized Filter to identify the entries to process.
	Filter        []byte `protobuf:"bytes,6,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeAllRequest) Reset() {
	*x = InvokeAllRequest{}
	mi := &file_messages_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeAllRequest) ProtoMessage() {}

func (x *InvokeAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeAllRequest.ProtoReflect.Descriptor instead.
func (*InvokeAllRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{25}
}

func (x *InvokeAllRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *InvokeAllRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *InvokeAllRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *InvokeAllRequest) GetProcessor() []byte {
	if x != nil {
		return x.Processor
	}
	return nil
}

func (x *InvokeAllRequest) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *InvokeAllRequest) GetFilter() []byte {
	if x != nil {
		return x.Filter
	}
	return nil
}

// A request to get a set of entries from a cache.
type EntrySetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	// The serialization format.
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// The serialized Filter to identify the entries to return.
	Filter []byte `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	// The optional comparator to use to sort the returned entries.
	Comparator    []byte `protobuf:"bytes,5,opt,name=comparator,proto3" json:"comparator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntrySetRequest) Reset() {
	*x = EntrySetRequest{}
	mi := &file_messages_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntrySetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntrySetRequest) ProtoMessage() {}

func (x *EntrySetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntrySetRequest.ProtoReflect.Descriptor instead.
func (*EntrySetRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{26}
}

func (x *EntrySetRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *EntrySetRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *EntrySetRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *EntrySetRequest) GetFilter() []byte {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *EntrySetRequest) GetComparator() []byte {
	if x != nil {
		return x.Comparator
	}
	return nil
}

// A request to get a set of keys from a cache.
type KeySetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	// The serialization format.
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// The serialized Filter to identify the keys to return.
	Filter        []byte `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeySetRequest) Reset() {
	*x = KeySetRequest{}
	mi := &file_messages_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeySetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeySetRequest) ProtoMessage() {}

func (x *KeySetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeySetRequest.ProtoReflect.Descriptor instead.
func (*KeySetRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{27}
}

func (x *KeySetRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *KeySetRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *KeySetRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *KeySetRequest) GetFilter() []byte {
	if x != nil {
		return x.Filter
	}
	return nil
}

// A request to get a collection of values from a cache.
type ValuesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	// The serialization format.
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// The serialized Filter to identify the values to return.
	Filter []byte `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	// The optional comparator to use to sort the returned values.
	Comparator    []byte `protobuf:"bytes,5,opt,name=comparator,proto3" json:"comparator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValuesRequest) Reset() {
	*x = ValuesRequest{}
	mi := &file_messages_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValuesRequest) ProtoMessage() {}

func (x *ValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValuesRequest.ProtoReflect.Descriptor instead.
func (*ValuesRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{28}
}

func (x *ValuesRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ValuesRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *ValuesRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ValuesRequest) GetFilter() []byte {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ValuesRequest) GetComparator() []byte {
	if x != nil {
		return x.Comparator
	}
	return nil
}

// An optional value.
type OptionalValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A flag indicating whether the value is present.
	Present bool `protobuf:"varint,1,opt,name=present,proto3" json:"present,omitempty"`
	// The serialized value.
	Value         []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalValue) Reset() {
	*x = OptionalValue{}
	mi := &file_messages_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalValue) ProtoMessage() {}

func (x *OptionalValue) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalValue.ProtoReflect.Descriptor instead.
func (*OptionalValue) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{29}
}

func (x *OptionalValue) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *OptionalValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// A message to subscribe to or unsubscribe from MapEvents for a cache.
type MapListenerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the cache.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// The name of the cache.
	Cache string `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	// The serialization format.
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// A unique identifier for the request so that the client
	// can match a request to a response
	Uid string `protobuf:"bytes,4,opt,name=uid,proto3" json:"uid,omitempty"`
	// The type of the request.
	Type MapListenerRequest_RequestType `protobuf:"varint,5,opt,name=type,proto3,enum=coherence.MapListenerRequest_RequestType" json:"type,omitempty"`
	// The serialized Filter to identify the entries to subscribe to.
	Filter []byte `protobuf:"bytes,6,opt,name=filter,proto3" json:"filter,omitempty"`
	// The serialized key to identify the entry to subscribe to.
	Key []byte `protobuf:"bytes,7,opt,name=key,proto3" json:"key,omitempty"`
	// A flag set to true to indicate that the MapEvent objects do
	// not have to include the OldValue and NewValue property values
	// in order to allow optimizations
	Lite bool `protobuf:"varint,8,opt,name=lite,proto3" json:"lite,omitempty"`
	// A flag indicating whether to subscribe to (true) or unsubscribe from (false) events.
	Subscribe bool `protobuf:"varint,9,opt,name=subscribe,proto3" json:"subscribe,omitempty"`
	// A flag set to true to indicate that the listener is a priming listener.
	Priming bool `protobuf:"varint,10,opt,name=priming,proto3" json:"priming,omitempty"`
	// An optional serialized MapTrigger.
	Trigger []byte `protobuf:"bytes,11,opt,name=trigger,proto3" json:"trigger,omitempty"`
	// A unique filter identifier.
	FilterId      int64 `protobuf:"varint,12,opt,name=filterId,proto3" json:"filterId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapListenerRequest) Reset() {
	*x = MapListenerRequest{}
	mi := &file_messages_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapListenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapListenerRequest) ProtoMessage() {}

func (x *MapListenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapListenerRequest.ProtoReflect.Descriptor instead.
func (*MapListenerRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{30}
}

func (x *MapListenerRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *MapListenerRequest) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

func (x *MapListenerRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *MapListenerRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *MapListenerRequest) GetType() MapListenerRequest_RequestType {
	if x != nil {
		return x.Type
	}
	return MapListenerRequest_INIT
}

func (x *MapListenerRequest) GetFilter() []byte {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *MapListenerRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *MapListenerRequest) GetLite() bool {
	if x != nil {
		return x.Lite
	}
	return false
}

func (x *MapListenerRequest) GetSubscribe() bool {
	if x != nil {
		return x.Subscribe
	}
	return false
}

func (x *MapListenerRequest) GetPriming() bool {
	if x != nil {
		return x.Priming
	}
	return false
}

func (x *MapListenerRequest) GetTrigger() []byte {
	if x != nil {
		return x.Trigger
	}
	return nil
}

func (x *MapListenerRequest) GetFilterId() int64 {
	if x != nil {
		return x.FilterId
	}
	return 0
}

// A response to indicate that a MapListener was subscribed to a cache.
type MapListenerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A response can be one of either a subscribed response or an event response.
	//
	// Types that are valid to be assigned to ResponseType:
	//
	//	*MapListenerResponse_Subscribed
	//	*MapListenerResponse_Unsubscribed
	//	*MapListenerResponse_Event
	//	*MapListenerResponse_Error
	//	*MapListenerResponse_Destroyed
	//	*MapListenerResponse_Truncated
	ResponseType  isMapListenerResponse_ResponseType `protobuf_oneof:"response_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapListenerResponse) Reset() {
	*x = MapListenerResponse{}
	mi := &file_messages_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapListenerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapListenerResponse) ProtoMessage() {}

func (x *MapListenerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapListenerResponse.ProtoReflect.Descriptor instead.
func (*MapListenerResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{31}
}

func (x *MapListenerResponse) GetResponseType() isMapListenerResponse_ResponseType {
	if x != nil {
		return x.ResponseType
	}
	return nil
}

func (x *MapListenerResponse) GetSubscribed() *MapListenerSubscribedResponse {
	if x != nil {
		if x, ok := x.ResponseType.(*MapListenerResponse_Subscribed); ok {
			return x.Subscribed
		}
	}
	return nil
}

func (x *MapListenerResponse) GetUnsubscribed() *MapListenerUnsubscribedResponse {
	if x != nil {
		if x, ok := x.ResponseType.(*MapListenerResponse_Unsubscribed); ok {
			return x.Unsubscribed
		}
	}
	return nil
}

func (x *MapListenerResponse) GetEvent() *MapEventResponse {
	if x != nil {
		if x, ok := x.ResponseType.(*MapListenerResponse_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *MapListenerResponse) GetError() *MapListenerErrorResponse {
	if x != nil {
		if x, ok := x.ResponseType.(*MapListenerResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *MapListenerResponse) GetDestroyed() *CacheDestroyedResponse {
	if x != nil {
		if x, ok := x.ResponseType.(*MapListenerResponse_Destroyed); ok {
			return x.Destroyed
		}
	}
	return nil
}

func (x *MapListenerResponse) GetTruncated() *CacheTruncatedResponse {
	if x != nil {
		if x, ok := x.ResponseType.(*MapListenerResponse_Truncated); ok {
			return x.Truncated
		}
	}
	return nil
}

type isMapListenerResponse_ResponseType interface {
	isMapListenerResponse_ResponseType()
}

type MapListenerResponse_Subscribed struct {
	Subscribed *MapListenerSubscribedResponse `protobuf:"bytes,1,opt,name=subscribed,proto3,oneof"`
}

type MapListenerResponse_Unsubscribed struct {
	Unsubscribed *MapListenerUnsubscribedResponse `protobuf:"bytes,2,opt,name=unsubscribed,proto3,oneof"`
}

type MapListenerResponse_Event struct {
	Event *MapEventResponse `protobuf:"bytes,3,opt,name=event,proto3,oneof"`
}

type MapListenerResponse_Error struct {
	Error *MapListenerErrorResponse `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

type MapListenerResponse_Destroyed struct {
	Destroyed *CacheDestroyedResponse `protobuf:"bytes,5,opt,name=destroyed,proto3,oneof"`
}

type MapListenerResponse_Truncated struct {
	Truncated *CacheTruncatedResponse `protobuf:"bytes,6,opt,name=truncated,proto3,oneof"`
}

func (*MapListenerResponse_Subscribed) isMapListenerResponse_ResponseType() {}

func (*MapListenerResponse_Unsubscribed) isMapListenerResponse_ResponseType() {}

func (*MapListenerResponse_Event) isMapListenerResponse_ResponseType() {}

func (*MapListenerResponse_Error) isMapListenerResponse_ResponseType() {}

func (*MapListenerResponse_Destroyed) isMapListenerResponse_ResponseType() {}

func (*MapListenerResponse_Truncated) isMapListenerResponse_ResponseType() {}

// A response to indicate that a MapListener was subscribed to a cache.
type MapListenerSubscribedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapListenerSubscribedResponse) Reset() {
	*x = MapListenerSubscribedResponse{}
	mi := &file_messages_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapListenerSubscribedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapListenerSubscribedResponse) ProtoMessage() {}

func (x *MapListenerSubscribedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapListenerSubscribedResponse.ProtoReflect.Descriptor instead.
func (*MapListenerSubscribedResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{32}
}

func (x *MapListenerSubscribedResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// A response to indicate that a MapListener was unsubscribed from a cache.
type MapListenerUnsubscribedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapListenerUnsubscribedResponse) Reset() {
	*x = MapListenerUnsubscribedResponse{}
	mi := &file_messages_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapListenerUnsubscribedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapListenerUnsubscribedResponse) ProtoMessage() {}

func (x *MapListenerUnsubscribedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapListenerUnsubscribedResponse.ProtoReflect.Descriptor instead.
func (*MapListenerUnsubscribedResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{33}
}

func (x *MapListenerUnsubscribedResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// A response to indicate that a cache was destroyed.
type CacheDestroyedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cache         string                 `protobuf:"bytes,1,opt,name=cache,proto3" json:"cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheDestroyedResponse) Reset() {
	*x = CacheDestroyedResponse{}
	mi := &file_messages_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheDestroyedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheDestroyedResponse) ProtoMessage() {}

func (x *CacheDestroyedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheDestroyedResponse.ProtoReflect.Descriptor instead.
func (*CacheDestroyedResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{34}
}

func (x *CacheDestroyedResponse) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

// A response to indicate that a cache was truncated.
type CacheTruncatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cache         string                 `protobuf:"bytes,1,opt,name=cache,proto3" json:"cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheTruncatedResponse) Reset() {
	*x = CacheTruncatedResponse{}
	mi := &file_messages_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheTruncatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheTruncatedResponse) ProtoMessage() {}

func (x *CacheTruncatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheTruncatedResponse.ProtoReflect.Descriptor instead.
func (*CacheTruncatedResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{35}
}

func (x *CacheTruncatedResponse) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

// A response to indicate that an error occurred processing a MapListener request.
type MapListenerErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Stack         []string               `protobuf:"bytes,4,rep,name=stack,proto3" json:"stack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapListenerErrorResponse) Reset() {
	*x = MapListenerErrorResponse{}
	mi := &file_messages_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapListenerErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapListenerErrorResponse) ProtoMessage() {}

func (x *MapListenerErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapListenerErrorResponse.ProtoReflect.Descriptor instead.
func (*MapListenerErrorResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{36}
}

func (x *MapListenerErrorResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *MapListenerErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MapListenerErrorResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MapListenerErrorResponse) GetStack() []string {
	if x != nil {
		return x.Stack
	}
	return nil
}

// A response containing a MapEvent for a MapListener
type MapEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of the event
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The key of the entry
	Key []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// The new value of the entry
	NewValue []byte `protobuf:"bytes,3,opt,name=newValue,proto3" json:"newValue,omitempty"`
	// The old value of the entry
	OldValue []byte `protobuf:"bytes,4,opt,name=oldValue,proto3" json:"oldValue,omitempty"`
	// TransformationState describes how a CacheEvent has been or should be transformed.
	TransformationState MapEventResponse_TransformationState `protobuf:"varint,5,opt,name=transformationState,proto3,enum=coherence.MapEventResponse_TransformationState" json:"transformationState,omitempty"`
	// The Filter identifiers applicable to the event.
	FilterIds []int64 `protobuf:"varint,6,rep,packed,name=filterIds,proto3" json:"filterIds,omitempty"`
	// A flag indicating whether the event is a synthetic event.
	Synthetic bool `protobuf:"varint,7,opt,name=synthetic,proto3" json:"synthetic,omitempty"`
	// A flag indicating whether the event is a priming event.
	Priming       bool `protobuf:"varint,8,opt,name=priming,proto3" json:"priming,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapEventResponse) Reset() {
	*x = MapEventResponse{}
	mi := &file_messages_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapEventResponse) ProtoMessage() {}

func (x *MapEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapEventResponse.ProtoReflect.Descriptor instead.
func (*MapEventResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{37}
}

func (x *MapEventResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MapEventResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *MapEventResponse) GetNewValue() []byte {
	if x != nil {
		return x.NewValue
	}
	return nil
}

func (x *MapEventResponse) GetOldValue() []byte {
	if x != nil {
		return x.OldValue
	}
	return nil
}

func (x *MapEventResponse) GetTransformationState() MapEventResponse_TransformationState {
	if x != nil {
		return x.TransformationState
	}
	return MapEventResponse_NON_TRANSFORMABLE
}

func (x *MapEventResponse) GetFilterIds() []int64 {
	if x != nil {
		return x.FilterIds
	}
	return nil
}

func (x *MapEventResponse) GetSynthetic() bool {
	if x != nil {
		return x.Synthetic
	}
	return false
}

func (x *MapEventResponse) GetPriming() bool {
	if x != nil {
		return x.Priming
	}
	return false
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\tcoherence\":\n" +
	"\fClearRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\"\x82\x01\n" +
	"\x14ContainsEntryRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x10\n" +
	"\x03key\x18\x04 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\"j\n" +
	"\x12ContainsKeyRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x10\n" +
	"\x03key\x18\x04 \x01(\fR\x03key\"p\n" +
	"\x14ContainsValueRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\"<\n" +
	"\x0eDestroyRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\"<\n" +
	"\x0eIsEmptyRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\"<\n" +
	"\x0eIsReadyRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\"9\n" +
	"\vSizeRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\"b\n" +
	"\n" +
	"GetRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x10\n" +
	"\x03key\x18\x04 \x01(\fR\x03key\"e\n" +
	"\rGetAllRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x10\n" +
	"\x03key\x18\x04 \x03(\fR\x03key\"\x8a\x01\n" +
	"\n" +
	"PutRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x10\n" +
	"\x03key\x18\x04 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\x12\x10\n" +
	"\x03ttl\x18\x06 \x01(\x03R\x03ttl\"\x8d\x01\n" +
	"\rPutAllRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12&\n" +
	"\x05entry\x18\x04 \x03(\v2\x10.coherence.EntryR\x05entry\x12\x10\n" +
	"\x03ttl\x18\x06 \x01(\x03R\x03ttl\"\x92\x01\n" +
	"\x12PutIfAbsentRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x10\n" +
	"\x03key\x18\x04 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\x12\x10\n" +
	"\x03ttl\x18\x06 \x01(\x03R\x03ttl\"e\n" +
	"\rRemoveRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x10\n" +
	"\x03key\x18\x04 \x01(\fR\x03key\"\x82\x01\n" +
	"\x14RemoveMappingRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x10\n" +
	"\x03key\x18\x04 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\"|\n" +
	"\x0eReplaceRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x10\n" +
	"\x03key\x18\x04 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\"\xaf\x01\n" +
	"\x15ReplaceMappingRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x10\n" +
	"\x03key\x18\x04 \x01(\fR\x03key\x12$\n" +
	"\rpreviousValue\x18\x05 \x01(\fR\rpreviousValue\x12\x1a\n" +
	"\bnewValue\x18\x06 \x01(\fR\bnewValue\"i\n" +
	"\vPageRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x16\n" +
	"\x06cookie\x18\x04 \x01(\fR\x06cookie\"M\n" +
	"\vEntryResult\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x16\n" +
	"\x06cookie\x18\x03 \x01(\fR\x06cookie\"/\n" +
	"\x05Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"=\n" +
	"\x0fTruncateRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\"\xab\x01\n" +
	"\x0fAddIndexRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x1c\n" +
	"\textractor\x18\x04 \x01(\fR\textractor\x12\x16\n" +
	"\x06sorted\x18\x05 \x01(\bR\x06sorted\x12\x1e\n" +
	"\n" +
	"comparator\x18\x06 \x01(\fR\n" +
	"comparator\"v\n" +
	"\x12RemoveIndexRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x1c\n" +
	"\textractor\x18\x04 \x01(\fR\textractor\"\xa2\x01\n" +
	"\x10AggregateRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x1e\n" +
	"\n" +
	"aggregator\x18\x04 \x01(\fR\n" +
	"aggregator\x12\x12\n" +
	"\x04keys\x18\x05 \x03(\fR\x04keys\x12\x16\n" +
	"\x06filter\x18\x06 \x01(\fR\x06filter\"\x83\x01\n" +
	"\rInvokeRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x1c\n" +
	"\tprocessor\x18\x04 \x01(\fR\tprocessor\x12\x10\n" +
	"\x03key\x18\x05 \x01(\fR\x03key\"\xa0\x01\n" +
	"\x10InvokeAllRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x1c\n" +
	"\tprocessor\x18\x04 \x01(\fR\tprocessor\x12\x12\n" +
	"\x04keys\x18\x05 \x03(\fR\x04keys\x12\x16\n" +
	"\x06filter\x18\x06 \x01(\fR\x06filter\"\x8d\x01\n" +
	"\x0fEntrySetRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\fR\x06filter\x12\x1e\n" +
	"\n" +
	"comparator\x18\x05 \x01(\fR\n" +
	"comparator\"k\n" +
	"\rKeySetRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\fR\x06filter\"\x8b\x01\n" +
	"\rValuesRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\fR\x06filter\x12\x1e\n" +
	"\n" +
	"comparator\x18\x05 \x01(\fR\n" +
	"comparator\"?\n" +
	"\rOptionalValue\x12\x18\n" +
	"\apresent\x18\x01 \x01(\bR\apresent\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\x83\x03\n" +
	"\x12MapListenerRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x14\n" +
	"\x05cache\x18\x02 \x01(\tR\x05cache\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\tR\x03uid\x12=\n" +
	"\x04type\x18\x05 \x01(\x0e2).coherence.MapListenerRequest.RequestTypeR\x04type\x12\x16\n" +
	"\x06filter\x18\x06 \x01(\fR\x06filter\x12\x10\n" +
	"\x03key\x18\a \x01(\fR\x03key\x12\x12\n" +
	"\x04lite\x18\b \x01(\bR\x04lite\x12\x1c\n" +
	"\tsubscribe\x18\t \x01(\bR\tsubscribe\x12\x18\n" +
	"\apriming\x18\n" +
	" \x01(\bR\apriming\x12\x18\n" +
	"\atrigger\x18\v \x01(\fR\atrigger\x12\x1a\n" +
	"\bfilterId\x18\f \x01(\x03R\bfilterId\",\n" +
	"\vRequestType\x12\b\n" +
	"\x04INIT\x10\x00\x12\a\n" +
	"\x03KEY\x10\x01\x12\n" +
	"\n" +
	"\x06FILTER\x10\x02\"\xbc\x03\n" +
	"\x13MapListenerResponse\x12J\n" +
	"\n" +
	"subscribed\x18\x01 \x01(\v2(.coherence.MapListenerSubscribedResponseH\x00R\n" +
	"subscribed\x12P\n" +
	"\funsubscribed\x18\x02 \x01(\v2*.coherence.MapListenerUnsubscribedResponseH\x00R\funsubscribed\x123\n" +
	"\x05event\x18\x03 \x01(\v2\x1b.coherence.MapEventResponseH\x00R\x05event\x12;\n" +
	"\x05error\x18\x04 \x01(\v2#.coherence.MapListenerErrorResponseH\x00R\x05error\x12A\n" +
	"\tdestroyed\x18\x05 \x01(\v2!.coherence.CacheDestroyedResponseH\x00R\tdestroyed\x12A\n" +
	"\ttruncated\x18\x06 \x01(\v2!.coherence.CacheTruncatedResponseH\x00R\ttruncatedB\x0f\n" +
	"\rresponse_type\"1\n" +
	"\x1dMapListenerSubscribedResponse\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"3\n" +
	"\x1fMapListenerUnsubscribedResponse\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\".\n" +
	"\x16CacheDestroyedResponse\x12\x14\n" +
	"\x05cache\x18\x01 \x01(\tR\x05cache\".\n" +
	"\x16CacheTruncatedResponse\x12\x14\n" +
	"\x05cache\x18\x01 \x01(\tR\x05cache\"p\n" +
	"\x18MapListenerErrorResponse\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\x12\x14\n" +
	"\x05stack\x18\x04 \x03(\tR\x05stack\"\xf7\x02\n" +
	"\x10MapEventResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x1a\n" +
	"\bnewValue\x18\x03 \x01(\fR\bnewValue\x12\x1a\n" +
	"\boldValue\x18\x04 \x01(\fR\boldValue\x12a\n" +
	"\x13transformationState\x18\x05 \x01(\x0e2/.coherence.MapEventResponse.TransformationStateR\x13transformationState\x12\x1c\n" +
	"\tfilterIds\x18\x06 \x03(\x03R\tfilterIds\x12\x1c\n" +
	"\tsynthetic\x18\a \x01(\bR\tsynthetic\x12\x18\n" +
	"\apriming\x18\b \x01(\bR\apriming\"P\n" +
	"\x13TransformationState\x12\x15\n" +
	"\x11NON_TRANSFORMABLE\x10\x00\x12\x11\n" +
	"\rTRANSFORMABLE\x10\x01\x12\x0f\n" +
	"\vTRANSFORMED\x10\x02BJ\n" +
	"\x19com.oracle.coherence.grpcP\x01Z+github.com/oracle/coherence-go-client/protob\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_messages_proto_goTypes = []any{
	(MapListenerRequest_RequestType)(0),       // 0: coherence.MapListenerRequest.RequestType
	(MapEventResponse_TransformationState)(0), // 1: coherence.MapEventResponse.TransformationState
	(*ClearRequest)(nil),                      // 2: coherence.ClearRequest
	(*ContainsEntryRequest)(nil),              // 3: coherence.ContainsEntryRequest
	(*ContainsKeyRequest)(nil),                // 4: coherence.ContainsKeyRequest
	(*ContainsValueRequest)(nil),              // 5: coherence.ContainsValueRequest
	(*DestroyRequest)(nil),                    // 6: coherence.DestroyRequest
	(*IsEmptyRequest)(nil),                    // 7: coherence.IsEmptyRequest
	(*IsReadyRequest)(nil),                    // 8: coherence.IsReadyRequest
	(*SizeRequest)(nil),                       // 9: coherence.SizeRequest
	(*GetRequest)(nil),                        // 10: coherence.GetRequest
	(*GetAllRequest)(nil),                     // 11: coherence.GetAllRequest
	(*PutRequest)(nil),                        // 12: coherence.PutRequest
	(*PutAllRequest)(nil),                     // 13: coherence.PutAllRequest
	(*PutIfAbsentRequest)(nil),                // 14: coherence.PutIfAbsentRequest
	(*RemoveRequest)(nil),                     // 15: coherence.RemoveRequest
	(*RemoveMappingRequest)(nil),              // 16: coherence.RemoveMappingRequest
	(*ReplaceRequest)(nil),                    // 17: coherence.ReplaceRequest
	(*ReplaceMappingRequest)(nil),             // 18: coherence.ReplaceMappingRequest
	(*PageRequest)(nil),                       // 19: coherence.PageRequest
	(*EntryResult)(nil),                       // 20: coherence.EntryResult
	(*Entry)(nil),                             // 21: coherence.Entry
	(*TruncateRequest)(nil),                   // 22: coherence.TruncateRequest
	(*AddIndexRequest)(nil),                   // 23: coherence.AddIndexRequest
	(*RemoveIndexRequest)(nil),                // 24: coherence.RemoveIndexRequest
	(*AggregateRequest)(nil),                  // 25: coherence.AggregateRequest
	(*InvokeRequest)(nil),                     // 26: coherence.InvokeRequest
	(*InvokeAllRequest)(nil),                  // 27: coherence.InvokeAllRequest
	(*EntrySetRequest)(nil),                   // 28: coherence.EntrySetRequest
	(*KeySetRequest)(nil),                     // 29: coherence.KeySetRequest
	(*ValuesRequest)(nil),                     // 30: coherence.ValuesRequest
	(*OptionalValue)(nil),                     // 31: coherence.OptionalValue
	(*MapListenerRequest)(nil),                // 32: coherence.MapListenerRequest
	(*MapListenerResponse)(nil),               // 33: coherence.MapListenerResponse
	(*MapListenerSubscribedResponse)(nil),     // 34: coherence.MapListenerSubscribedResponse
	(*MapListenerUnsubscribedResponse)(nil),   // 35: coherence.MapListenerUnsubscribedResponse
	(*CacheDestroyedResponse)(nil),            // 36: coherence.CacheDestroyedResponse
	(*CacheTruncatedResponse)(nil),            // 37: coherence.CacheTruncatedResponse
	(*MapListenerErrorResponse)(nil),          // 38: coherence.MapListenerErrorResponse
	(*MapEventResponse)(nil),                  // 39: coherence.MapEventResponse
}
var file_messages_proto_depIdxs = []int32{
	21, // 0: coherence.PutAllRequest.entry:type_name -> coherence.Entry
	0,  // 1: coherence.MapListenerRequest.type:type_name -> coherence.MapListenerRequest.RequestType
	34, // 2: coherence.MapListenerResponse.subscribed:type_name -> coherence.MapListenerSubscribedResponse
	35, // 3: coherence.MapListenerResponse.unsubscribed:type_name -> coherence.MapListenerUnsubscribedResponse
	39, // 4: coherence.MapListenerResponse.event:type_name -> coherence.MapEventResponse
	38, // 5: coherence.MapListenerResponse.error:type_name -> coherence.MapListenerErrorResponse
	36, // 6: coherence.MapListenerResponse.destroyed:type_name -> coherence.CacheDestroyedResponse
	37, // 7: coherence.MapListenerResponse.truncated:type_name -> coherence.CacheTruncatedResponse
	1,  // 8: coherence.MapEventResponse.transformationState:type_name -> coherence.MapEventResponse.TransformationState
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	file_messages_proto_msgTypes[31].OneofWrappers = []any{
		(*MapListenerResponse_Subscribed)(nil),
		(*MapListenerResponse_Unsubscribed)(nil),
		(*MapListenerResponse_Event)(nil),
		(*MapListenerResponse_Error)(nil),
		(*MapListenerResponse_Destroyed)(nil),
		(*MapListenerResponse_Truncated)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
