//
// Copyright (c) 2020, 2023, Oracle and/or its affiliates.
//
// Licensed under the Universal Permissive License v 1.0 as shown at
// https://oss.oracle.com/licenses/upl.

// Authors:
//  Mahesh Kannan
//  Jonathan Knight

// NamedCacheService service definition.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.2
// source: services.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_services_proto protoreflect.FileDescriptor

const file_services_proto_rawDesc = "" +
	"\n" +
	"\x0eservices.proto\x12\tcoherence\x1a\x0emessages.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto2\xea\x0f\n" +
	"\x11NamedCacheService\x12@\n" +
	"\baddIndex\x12\x1a.coherence.AddIndexRequest\x1a\x16.google.protobuf.Empty\"\x00\x12G\n" +
	"\taggregate\x12\x1b.coherence.AggregateRequest\x1a\x1b.google.protobuf.BytesValue\"\x00\x12:\n" +
	"\x05clear\x12\x17.coherence.ClearRequest\x1a\x16.google.protobuf.Empty\"\x00\x12N\n" +
	"\rcontainsEntry\x12\x1f.coherence.ContainsEntryRequest\x1a\x1a.google.protobuf.BoolValue\"\x00\x12J\n" +
	"\vcontainsKey\x12\x1d.coherence.ContainsKeyRequest\x1a\x1a.google.protobuf.BoolValue\"\x00\x12N\n" +
	"\rcontainsValue\x12\x1f.coherence.ContainsValueRequest\x1a\x1a.google.protobuf.BoolValue\"\x00\x12>\n" +
	"\adestroy\x12\x19.coherence.DestroyRequest\x1a\x16.google.protobuf.Empty\"\x00\x12<\n" +
	"\bentrySet\x12\x1a.coherence.EntrySetRequest\x1a\x10.coherence.Entry\"\x000\x01\x12M\n" +
	"\x06events\x12\x1d.coherence.MapListenerRequest\x1a\x1e.coherence.MapListenerResponse\"\x00(\x010\x01\x128\n" +
	"\x03get\x12\x15.coherence.GetRequest\x1a\x18.coherence.OptionalValue\"\x00\x128\n" +
	"\x06getAll\x12\x18.coherence.GetAllRequest\x1a\x10.coherence.Entry\"\x000\x01\x12A\n" +
	"\x06invoke\x12\x18.coherence.InvokeRequest\x1a\x1b.google.protobuf.BytesValue\"\x00\x12>\n" +
	"\tinvokeAll\x12\x1b.coherence.InvokeAllRequest\x1a\x10.coherence.Entry\"\x000\x01\x12B\n" +
	"\aisEmpty\x12\x19.coherence.IsEmptyRequest\x1a\x1a.google.protobuf.BoolValue\"\x00\x12B\n" +
	"\aisReady\x12\x19.coherence.IsReadyRequest\x1a\x1a.google.protobuf.BoolValue\"\x00\x12C\n" +
	"\x06keySet\x12\x18.coherence.KeySetRequest\x1a\x1b.google.protobuf.BytesValue\"\x000\x01\x12F\n" +
	"\x10nextEntrySetPage\x12\x16.coherence.PageRequest\x1a\x16.coherence.EntryResult\"\x000\x01\x12I\n" +
	"\x0enextKeySetPage\x12\x16.coherence.PageRequest\x1a\x1b.google.protobuf.BytesValue\"\x000\x01\x12;\n" +
	"\x03put\x12\x15.coherence.PutRequest\x1a\x1b.google.protobuf.BytesValue\"\x00\x12<\n" +
	"\x06putAll\x12\x18.coherence.PutAllRequest\x1a\x16.google.protobuf.Empty\"\x00\x12K\n" +
	"\vputIfAbsent\x12\x1d.coherence.PutIfAbsentRequest\x1a\x1b.google.protobuf.BytesValue\"\x00\x12A\n" +
	"\x06remove\x12\x18.coherence.RemoveRequest\x1a\x1b.google.protobuf.BytesValue\"\x00\x12F\n" +
	"\vremoveIndex\x12\x1d.coherence.RemoveIndexRequest\x1a\x16.google.protobuf.Empty\"\x00\x12N\n" +
	"\rremoveMapping\x12\x1f.coherence.RemoveMappingRequest\x1a\x1a.google.protobuf.BoolValue\"\x00\x12C\n" +
	"\areplace\x12\x19.coherence.ReplaceRequest\x1a\x1b.google.protobuf.BytesValue\"\x00\x12P\n" +
	"\x0ereplaceMapping\x12 .coherence.ReplaceMappingRequest\x1a\x1a.google.protobuf.BoolValue\"\x00\x12=\n" +
	"\x04size\x12\x16.coherence.SizeRequest\x1a\x1b.google.protobuf.Int32Value\"\x00\x12@\n" +
	"\btruncate\x12\x1a.coherence.TruncateRequest\x1a\x16.google.protobuf.Empty\"\x00\x12C\n" +
	"\x06values\x12\x18.coherence.ValuesRequest\x1a\x1b.google.protobuf.BytesValue\"\x000\x01BJ\n" +
	"\x19com.oracle.coherence.grpcP\x01Z+github.com/oracle/coherence-go-client/protob\x06proto3"

var file_services_proto_goTypes = []any{
	(*AddIndexRequest)(nil),       // 0: coherence.AddIndexRequest
	(*AggregateRequest)(nil),      // 1: coherence.AggregateRequest
	(*ClearRequest)(nil),          // 2: coherence.ClearRequest
	(*ContainsEntryRequest)(nil),  // 3: coherence.ContainsEntryRequest
	(*ContainsKeyRequest)(nil),    // 4: coherence.ContainsKeyRequest
	(*ContainsValueRequest)(nil),  // 5: coherence.ContainsValueRequest
	(*DestroyRequest)(nil),        // 6: coherence.DestroyRequest
	(*EntrySetRequest)(nil),       // 7: coherence.EntrySetRequest
	(*MapListenerRequest)(nil),    // 8: coherence.MapListenerRequest
	(*GetRequest)(nil),            // 9: coherence.GetRequest
	(*GetAllRequest)(nil),         // 10: coherence.GetAllRequest
	(*InvokeRequest)(nil),         // 11: coherence.InvokeRequest
	(*InvokeAllRequest)(nil),      // 12: coherence.InvokeAllRequest
	(*IsEmptyRequest)(nil),        // 13: coherence.IsEmptyRequest
	(*IsReadyRequest)(nil),        // 14: coherence.IsReadyRequest
	(*KeySetRequest)(nil),         // 15: coherence.KeySetRequest
	(*PageRequest)(nil),           // 16: coherence.PageRequest
	(*PutRequest)(nil),            // 17: coherence.PutRequest
	(*PutAllRequest)(nil),         // 18: coherence.PutAllRequest
	(*PutIfAbsentRequest)(nil),    // 19: coherence.PutIfAbsentRequest
	(*RemoveRequest)(nil),         // 20: coherence.RemoveRequest
	(*RemoveIndexRequest)(nil),    // 21: coherence.RemoveIndexRequest
	(*RemoveMappingRequest)(nil),  // 22: coherence.RemoveMappingRequest
	(*ReplaceRequest)(nil),        // 23: coherence.ReplaceRequest
	(*ReplaceMappingRequest)(nil), // 24: coherence.ReplaceMappingRequest
	(*SizeRequest)(nil),           // 25: coherence.SizeRequest
	(*TruncateRequest)(nil),       // 26: coherence.TruncateRequest
	(*ValuesRequest)(nil),         // 27: coherence.ValuesRequest
	(*emptypb.Empty)(nil),         // 28: google.protobuf.Empty
	(*wrapperspb.BytesValue)(nil), // 29: google.protobuf.BytesValue
	(*wrapperspb.BoolValue)(nil),  // 30: google.protobuf.BoolValue
	(*Entry)(nil),                 // 31: coherence.Entry
	(*MapListenerResponse)(nil),   // 32: coherence.MapListenerResponse
	(*OptionalValue)(nil),         // 33: coherence.OptionalValue
	(*EntryResult)(nil),           // 34: coherence.EntryResult
	(*wrapperspb.Int32Value)(nil), // 35: google.protobuf.Int32Value
}
var file_services_proto_depIdxs = []int32{
	0,  // 0: coherence.NamedCacheService.addIndex:input_type -> coherence.AddIndexRequest
	1,  // 1: coherence.NamedCacheService.aggregate:input_type -> coherence.AggregateRequest
	2,  // 2: coherence.NamedCacheService.clear:input_type -> coherence.ClearRequest
	3,  // 3: coherence.NamedCacheService.containsEntry:input_type -> coherence.ContainsEntryRequest
	4,  // 4: coherence.NamedCacheService.containsKey:input_type -> coherence.ContainsKeyRequest
	5,  // 5: coherence.NamedCacheService.containsValue:input_type -> coherence.ContainsValueRequest
	6,  // 6: coherence.NamedCacheService.destroy:input_type -> coherence.DestroyRequest
	7,  // 7: coherence.NamedCacheService.entrySet:input_type -> coherence.EntrySetRequest
	8,  // 8: coherence.NamedCacheService.events:input_type -> coherence.MapListenerRequest
	9,  // 9: coherence.NamedCacheService.get:input_type -> coherence.GetRequest
	10, // 10: coherence.NamedCacheService.getAll:input_type -> coherence.GetAllRequest
	11, // 11: coherence.NamedCacheService.invoke:input_type -> coherence.InvokeRequest
	12, // 12: coherence.NamedCacheService.invokeAll:input_type -> coherence.InvokeAllRequest
	13, // 13: coherence.NamedCacheService.isEmpty:input_type -> coherence.IsEmptyRequest
	14, // 14: coherence.NamedCacheService.isReady:input_type -> coherence.IsReadyRequest
	15, // 15: coherence.NamedCacheService.keySet:input_type -> coherence.KeySetRequest
	16, // 16: coherence.NamedCacheService.nextEntrySetPage:input_type -> coherence.PageRequest
	16, // 17: coherence.NamedCacheService.nextKeySetPage:input_type -> coherence.PageRequest
	17, // 18: coherence.NamedCacheService.put:input_type -> coherence.PutRequest
	18, // 19: coherence.NamedCacheService.putAll:input_type -> coherence.PutAllRequest
	19, // 20: coherence.NamedCacheService.putIfAbsent:input_type -> coherence.PutIfAbsentRequest
	20, // 21: coherence.NamedCacheService.remove:input_type -> coherence.RemoveRequest
	21, // 22: coherence.NamedCacheService.removeIndex:input_type -> coherence.RemoveIndexRequest
	22, // 23: coherence.NamedCacheService.removeMapping:input_type -> coherence.RemoveMappingRequest
	23, // 24: coherence.NamedCacheService.replace:input_type -> coherence.ReplaceRequest
	24, // 25: coherence.NamedCacheService.replaceMapping:input_type -> coherence.ReplaceMappingRequest
	25, // 26: coherence.NamedCacheService.size:input_type -> coherence.SizeRequest
	26, // 27: coherence.NamedCacheService.truncate:input_type -> coherence.TruncateRequest
	27, // 28: coherence.NamedCacheService.values:input_type -> coherence.ValuesRequest
	28, // 29: coherence.NamedCacheService.addIndex:output_type -> google.protobuf.Empty
	29, // 30: coherence.NamedCacheService.aggregate:output_type -> google.protobuf.BytesValue
	28, // 31: coherence.NamedCacheService.clear:output_type -> google.protobuf.Empty
	30, // 32: coherence.NamedCacheService.containsEntry:output_type -> google.protobuf.BoolValue
	30, // 33: coherence.NamedCacheService.containsKey:output_type -> google.protobuf.BoolValue
	30, // 34: coherence.NamedCacheService.containsValue:output_type -> google.protobuf.BoolValue
	28, // 35: coherence.NamedCacheService.destroy:output_type -> google.protobuf.Empty
	31, // 36: coherence.NamedCacheService.entrySet:output_type -> coherence.Entry
	32, // 37: coherence.NamedCacheService.events:output_type -> coherence.MapListenerResponse
	33, // 38: coherence.NamedCacheService.get:output_type -> coherence.OptionalValue
	31, // 39: coherence.NamedCacheService.getAll:output_type -> coherence.Entry
	29, // 40: coherence.NamedCacheService.invoke:output_type -> google.protobuf.BytesValue
	31, // 41: coherence.NamedCacheService.invokeAll:output_type -> coherence.Entry
	30, // 42: coherence.NamedCacheService.isEmpty:output_type -> google.protobuf.BoolValue
	30, // 43: coherence.NamedCacheService.isReady:output_type -> google.protobuf.BoolValue
	29, // 44: coherence.NamedCacheService.keySet:output_type -> google.protobuf.BytesValue
	34, // 45: coherence.NamedCacheService.nextEntrySetPage:output_type -> coherence.EntryResult
	29, // 46: coherence.NamedCacheService.nextKeySetPage:output_type -> google.protobuf.BytesValue
	29, // 47: coherence.NamedCacheService.put:output_type -> google.protobuf.BytesValue
	28, // 48: coherence.NamedCacheService.putAll:output_type -> google.protobuf.Empty
	29, // 49: coherence.NamedCacheService.putIfAbsent:output_type -> google.protobuf.BytesValue
	29, // 50: coherence.NamedCacheService.remove:output_type -> google.protobuf.BytesValue
	28, // 51: coherence.NamedCacheService.removeIndex:output_type -> google.protobuf.Empty
	30, // 52: coherence.NamedCacheService.removeMapping:output_type -> google.protobuf.BoolValue
	29, // 53: coherence.NamedCacheService.replace:output_type -> google.protobuf.BytesValue
	30, // 54: coherence.NamedCacheService.replaceMapping:output_type -> google.protobuf.BoolValue
	35, // 55: coherence.NamedCacheService.size:output_type -> google.protobuf.Int32Value
	28, // 56: coherence.NamedCacheService.truncate:output_type -> google.protobuf.Empty
	29, // 57: coherence.NamedCacheService.values:output_type -> google.protobuf.BytesValue
	29, // [29:58] is the sub-list for method output_type
	0,  // [0:29] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_services_proto_init() }
func file_services_proto_init() {
	if File_services_proto != nil {
		return
	}
	file_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_proto_rawDesc), len(file_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_proto_goTypes,
		DependencyIndexes: file_services_proto_depIdxs,
	}.Build()
	File_services_proto = out.File
	file_services_proto_goTypes = nil
	file_services_proto_depIdxs = nil
}
