//
// Copyright (c) 2020, 2025, Oracle and/or its affiliates.
//
// Licensed under the Universal Permissive License v 1.0 as shown at
// https://oss.oracle.com/licenses/upl.

// -----------------------------------------------------------------
// Common messages used by various Coherence services.
// -----------------------------------------------------------------

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.2
// source: common_messages_v1.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An error message
type ErrorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The text of the error message
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// An optional Exception serialized using the client's serializer
	Error         []byte `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_common_messages_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_common_messages_v1_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorMessage) GetError() []byte {
	if x != nil {
		return x.Error
	}
	return nil
}

// A message to indicate completion of a request response.
type Complete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Complete) Reset() {
	*x = Complete{}
	mi := &file_common_messages_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Complete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Complete) ProtoMessage() {}

func (x *Complete) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Complete.ProtoReflect.Descriptor instead.
func (*Complete) Descriptor() ([]byte, []int) {
	return file_common_messages_v1_proto_rawDescGZIP(), []int{1}
}

// A heart beat message.
type HeartbeatMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The UUID of the client
	Uuid []byte `protobuf:"bytes,1,opt,name=uuid,proto3,oneof" json:"uuid,omitempty"`
	// True to send a heartbeat response
	Ack           bool `protobuf:"varint,2,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatMessage) Reset() {
	*x = HeartbeatMessage{}
	mi := &file_common_messages_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMessage) ProtoMessage() {}

func (x *HeartbeatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMessage.ProtoReflect.Descriptor instead.
func (*HeartbeatMessage) Descriptor() ([]byte, []int) {
	return file_common_messages_v1_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatMessage) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *HeartbeatMessage) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

// An optional value.
type OptionalValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A flag indicating whether the value is present.
	Present bool `protobuf:"varint,1,opt,name=present,proto3" json:"present,omitempty"`
	// The serialized value.
	Value         []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalValue) Reset() {
	*x = OptionalValue{}
	mi := &file_common_messages_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalValue) ProtoMessage() {}

func (x *OptionalValue) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalValue.ProtoReflect.Descriptor instead.
func (*OptionalValue) Descriptor() ([]byte, []int) {
	return file_common_messages_v1_proto_rawDescGZIP(), []int{3}
}

func (x *OptionalValue) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *OptionalValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// A message that contains a collection of serialized binary values.
type CollectionOfBytesValues struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The serialized values
	Values        [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionOfBytesValues) Reset() {
	*x = CollectionOfBytesValues{}
	mi := &file_common_messages_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionOfBytesValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionOfBytesValues) ProtoMessage() {}

func (x *CollectionOfBytesValues) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionOfBytesValues.ProtoReflect.Descriptor instead.
func (*CollectionOfBytesValues) Descriptor() ([]byte, []int) {
	return file_common_messages_v1_proto_rawDescGZIP(), []int{4}
}

func (x *CollectionOfBytesValues) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

// A message containing a serialized key and value.
type BinaryKeyAndValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The serialized binary key.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The serialized binary value.
	Value         []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryKeyAndValue) Reset() {
	*x = BinaryKeyAndValue{}
	mi := &file_common_messages_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryKeyAndValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryKeyAndValue) ProtoMessage() {}

func (x *BinaryKeyAndValue) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryKeyAndValue.ProtoReflect.Descriptor instead.
func (*BinaryKeyAndValue) Descriptor() ([]byte, []int) {
	return file_common_messages_v1_proto_rawDescGZIP(), []int{5}
}

func (x *BinaryKeyAndValue) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *BinaryKeyAndValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// A message that contains a collection of string values.
type CollectionOfStringValues struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The string values
	Values        []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionOfStringValues) Reset() {
	*x = CollectionOfStringValues{}
	mi := &file_common_messages_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionOfStringValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionOfStringValues) ProtoMessage() {}

func (x *CollectionOfStringValues) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionOfStringValues.ProtoReflect.Descriptor instead.
func (*CollectionOfStringValues) Descriptor() ([]byte, []int) {
	return file_common_messages_v1_proto_rawDescGZIP(), []int{6}
}

func (x *CollectionOfStringValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// A collection of in32 values
type CollectionOfInt32 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []int32                `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionOfInt32) Reset() {
	*x = CollectionOfInt32{}
	mi := &file_common_messages_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionOfInt32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionOfInt32) ProtoMessage() {}

func (x *CollectionOfInt32) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionOfInt32.ProtoReflect.Descriptor instead.
func (*CollectionOfInt32) Descriptor() ([]byte, []int) {
	return file_common_messages_v1_proto_rawDescGZIP(), []int{7}
}

func (x *CollectionOfInt32) GetValues() []int32 {
	if x != nil {
		return x.Values
	}
	return nil
}

// A collection of in32 values
type CollectionOfInt64 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []int64                `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionOfInt64) Reset() {
	*x = CollectionOfInt64{}
	mi := &file_common_messages_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionOfInt64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionOfInt64) ProtoMessage() {}

func (x *CollectionOfInt64) ProtoReflect() protoreflect.Message {
	mi := &file_common_messages_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionOfInt64.ProtoReflect.Descriptor instead.
func (*CollectionOfInt64) Descriptor() ([]byte, []int) {
	return file_common_messages_v1_proto_rawDescGZIP(), []int{8}
}

func (x *CollectionOfInt64) GetValues() []int64 {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_common_messages_v1_proto protoreflect.FileDescriptor

const file_common_messages_v1_proto_rawDesc = "" +
	"\n" +
	"\x18common_messages_v1.proto\x12\x13coherence.common.v1\x1a\x19google/protobuf/any.proto\"M\n" +
	"\fErrorMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x19\n" +
	"\x05error\x18\x02 \x01(\fH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\n" +
	"\n" +
	"\bComplete\"F\n" +
	"\x10HeartbeatMessage\x12\x17\n" +
	"\x04uuid\x18\x01 \x01(\fH\x00R\x04uuid\x88\x01\x01\x12\x10\n" +
	"\x03ack\x18\x02 \x01(\bR\x03ackB\a\n" +
	"\x05_uuid\"?\n" +
	"\rOptionalValue\x12\x18\n" +
	"\apresent\x18\x01 \x01(\bR\apresent\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"1\n" +
	"\x17CollectionOfBytesValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\";\n" +
	"\x11BinaryKeyAndValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"2\n" +
	"\x18CollectionOfStringValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"+\n" +
	"\x11CollectionOfInt32\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x05R\x06values\"+\n" +
	"\x11CollectionOfInt64\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x03R\x06valuesB`\n" +
	",com.oracle.coherence.grpc.messages.common.v1P\x01Z.github.com/oracle/coherence-go-client/proto/v1b\x06proto3"

var (
	file_common_messages_v1_proto_rawDescOnce sync.Once
	file_common_messages_v1_proto_rawDescData []byte
)

func file_common_messages_v1_proto_rawDescGZIP() []byte {
	file_common_messages_v1_proto_rawDescOnce.Do(func() {
		file_common_messages_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_messages_v1_proto_rawDesc), len(file_common_messages_v1_proto_rawDesc)))
	})
	return file_common_messages_v1_proto_rawDescData
}

var file_common_messages_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_common_messages_v1_proto_goTypes = []any{
	(*ErrorMessage)(nil),             // 0: coherence.common.v1.ErrorMessage
	(*Complete)(nil),                 // 1: coherence.common.v1.Complete
	(*HeartbeatMessage)(nil),         // 2: coherence.common.v1.HeartbeatMessage
	(*OptionalValue)(nil),            // 3: coherence.common.v1.OptionalValue
	(*CollectionOfBytesValues)(nil),  // 4: coherence.common.v1.CollectionOfBytesValues
	(*BinaryKeyAndValue)(nil),        // 5: coherence.common.v1.BinaryKeyAndValue
	(*CollectionOfStringValues)(nil), // 6: coherence.common.v1.CollectionOfStringValues
	(*CollectionOfInt32)(nil),        // 7: coherence.common.v1.CollectionOfInt32
	(*CollectionOfInt64)(nil),        // 8: coherence.common.v1.CollectionOfInt64
}
var file_common_messages_v1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_messages_v1_proto_init() }
func file_common_messages_v1_proto_init() {
	if File_common_messages_v1_proto != nil {
		return
	}
	file_common_messages_v1_proto_msgTypes[0].OneofWrappers = []any{}
	file_common_messages_v1_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_messages_v1_proto_rawDesc), len(file_common_messages_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_messages_v1_proto_goTypes,
		DependencyIndexes: file_common_messages_v1_proto_depIdxs,
		MessageInfos:      file_common_messages_v1_proto_msgTypes,
	}.Build()
	File_common_messages_v1_proto = out.File
	file_common_messages_v1_proto_goTypes = nil
	file_common_messages_v1_proto_depIdxs = nil
}
