//
// Copyright (c) 2020, 2025, Oracle and/or its affiliates.
//
// Licensed under the Universal Permissive License v 1.0 as shown at
// https://oss.oracle.com/licenses/upl.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.2
// source: proxy_service_messages_v1.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A request to the Coherence gRPC proxy.
// Except for a Heartbeat, every request must have a unique id field.
type ProxyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Request:
	//
	//	*ProxyRequest_Init
	//	*ProxyRequest_Message
	//	*ProxyRequest_Heartbeat
	Request isProxyRequest_Request `protobuf_oneof:"request"`
	// An ad-hoc set of additional data.
	Context       map[string]*anypb.Any `protobuf:"bytes,6,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyRequest) Reset() {
	*x = ProxyRequest{}
	mi := &file_proxy_service_messages_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRequest) ProtoMessage() {}

func (x *ProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_service_messages_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRequest.ProtoReflect.Descriptor instead.
func (*ProxyRequest) Descriptor() ([]byte, []int) {
	return file_proxy_service_messages_v1_proto_rawDescGZIP(), []int{0}
}

func (x *ProxyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProxyRequest) GetRequest() isProxyRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ProxyRequest) GetInit() *InitRequest {
	if x != nil {
		if x, ok := x.Request.(*ProxyRequest_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *ProxyRequest) GetMessage() *anypb.Any {
	if x != nil {
		if x, ok := x.Request.(*ProxyRequest_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *ProxyRequest) GetHeartbeat() *HeartbeatMessage {
	if x != nil {
		if x, ok := x.Request.(*ProxyRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ProxyRequest) GetContext() map[string]*anypb.Any {
	if x != nil {
		return x.Context
	}
	return nil
}

type isProxyRequest_Request interface {
	isProxyRequest_Request()
}

type ProxyRequest_Init struct {
	// The initialization request, which must be the first request sent.
	Init *InitRequest `protobuf:"bytes,3,opt,name=init,proto3,oneof"`
}

type ProxyRequest_Message struct {
	// A message that is specific to a Coherence gRPC service.
	// Each service on the proxy will know what type to expect here.
	Message *anypb.Any `protobuf:"bytes,4,opt,name=message,proto3,oneof"`
}

type ProxyRequest_Heartbeat struct {
	// A periodic heartbeat message sent by the client
	Heartbeat *HeartbeatMessage `protobuf:"bytes,5,opt,name=heartbeat,proto3,oneof"`
}

func (*ProxyRequest_Init) isProxyRequest_Request() {}

func (*ProxyRequest_Message) isProxyRequest_Request() {}

func (*ProxyRequest_Heartbeat) isProxyRequest_Request() {}

// A response from a Coherence gRPC proxy.
// Except for a Heartbeat, every response will contain an id field
// that corresponds to the id of the request that the response if for.
type ProxyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier of the request messages this response is for, or zero if
	// this message is non-request related, for example it is an event.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The actual response message.
	//
	// Types that are valid to be assigned to Response:
	//
	//	*ProxyResponse_Init
	//	*ProxyResponse_Message
	//	*ProxyResponse_Error
	//	*ProxyResponse_Complete
	//	*ProxyResponse_Heartbeat
	Response isProxyResponse_Response `protobuf_oneof:"response"`
	// An ad-hoc set of additional data.
	Context       map[string]*anypb.Any `protobuf:"bytes,9,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyResponse) Reset() {
	*x = ProxyResponse{}
	mi := &file_proxy_service_messages_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyResponse) ProtoMessage() {}

func (x *ProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_service_messages_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyResponse.ProtoReflect.Descriptor instead.
func (*ProxyResponse) Descriptor() ([]byte, []int) {
	return file_proxy_service_messages_v1_proto_rawDescGZIP(), []int{1}
}

func (x *ProxyResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProxyResponse) GetResponse() isProxyResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ProxyResponse) GetInit() *InitResponse {
	if x != nil {
		if x, ok := x.Response.(*ProxyResponse_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *ProxyResponse) GetMessage() *anypb.Any {
	if x != nil {
		if x, ok := x.Response.(*ProxyResponse_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *ProxyResponse) GetError() *ErrorMessage {
	if x != nil {
		if x, ok := x.Response.(*ProxyResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ProxyResponse) GetComplete() *Complete {
	if x != nil {
		if x, ok := x.Response.(*ProxyResponse_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

func (x *ProxyResponse) GetHeartbeat() *HeartbeatMessage {
	if x != nil {
		if x, ok := x.Response.(*ProxyResponse_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ProxyResponse) GetContext() map[string]*anypb.Any {
	if x != nil {
		return x.Context
	}
	return nil
}

type isProxyResponse_Response interface {
	isProxyResponse_Response()
}

type ProxyResponse_Init struct {
	// The response to the initial InitRequest.
	Init *InitResponse `protobuf:"bytes,4,opt,name=init,proto3,oneof"`
}

type ProxyResponse_Message struct {
	// A response of a type specific to a Coherence gRPC service.
	// The client that sent the corresponding request will know what
	// type of message it expects in this field.
	Message *anypb.Any `protobuf:"bytes,5,opt,name=message,proto3,oneof"`
}

type ProxyResponse_Error struct {
	// An error response to a specific request id
	Error *ErrorMessage `protobuf:"bytes,6,opt,name=error,proto3,oneof"`
}

type ProxyResponse_Complete struct {
	// A complete message is sent to indicate that a stream of messages for
	// the same request id have been completed.
	Complete *Complete `protobuf:"bytes,7,opt,name=complete,proto3,oneof"`
}

type ProxyResponse_Heartbeat struct {
	// A periodic heart beat sent by the server
	Heartbeat *HeartbeatMessage `protobuf:"bytes,8,opt,name=heartbeat,proto3,oneof"`
}

func (*ProxyResponse_Init) isProxyResponse_Response() {}

func (*ProxyResponse_Message) isProxyResponse_Response() {}

func (*ProxyResponse_Error) isProxyResponse_Response() {}

func (*ProxyResponse_Complete) isProxyResponse_Response() {}

func (*ProxyResponse_Heartbeat) isProxyResponse_Response() {}

// Initialize a connection.
type InitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope name to use to obtain the server resources.
	Scope string `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	// The serialization format to use.
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// The protocol to use for the channel
	Protocol string `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// The protocol version requested by the client
	ProtocolVersion int32 `protobuf:"varint,5,opt,name=protocolVersion,proto3" json:"protocolVersion,omitempty"`
	// The minimum protocol version supported by the client
	SupportedProtocolVersion int32 `protobuf:"varint,6,opt,name=supportedProtocolVersion,proto3" json:"supportedProtocolVersion,omitempty"`
	// The requested frequency that heartbeat messages should be sent by the server (in millis)
	Heartbeat *int64 `protobuf:"varint,7,opt,name=heartbeat,proto3,oneof" json:"heartbeat,omitempty"`
	// The optional client UUID (usually from Coherence clients that have a local Member UUID).
	ClientUuid []byte `protobuf:"bytes,8,opt,name=clientUuid,proto3,oneof" json:"clientUuid,omitempty"`
	// The client's member identity
	Identity      *ClientMemberIdentity `protobuf:"bytes,9,opt,name=identity,proto3,oneof" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_proxy_service_messages_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_service_messages_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_proxy_service_messages_v1_proto_rawDescGZIP(), []int{2}
}

func (x *InitRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *InitRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *InitRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *InitRequest) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *InitRequest) GetSupportedProtocolVersion() int32 {
	if x != nil {
		return x.SupportedProtocolVersion
	}
	return 0
}

func (x *InitRequest) GetHeartbeat() int64 {
	if x != nil && x.Heartbeat != nil {
		return *x.Heartbeat
	}
	return 0
}

func (x *InitRequest) GetClientUuid() []byte {
	if x != nil {
		return x.ClientUuid
	}
	return nil
}

func (x *InitRequest) GetIdentity() *ClientMemberIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

// The response to an InitRequest
type InitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This client connection's UUID.
	Uuid []byte `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// The Coherence version of the proxy
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// The encoded version of the proxy
	EncodedVersion int32 `protobuf:"varint,3,opt,name=encodedVersion,proto3" json:"encodedVersion,omitempty"`
	// The protocol version the client should use
	ProtocolVersion int32 `protobuf:"varint,4,opt,name=protocolVersion,proto3" json:"protocolVersion,omitempty"`
	// The proxy member Id
	ProxyMemberId int32 `protobuf:"varint,5,opt,name=proxyMemberId,proto3" json:"proxyMemberId,omitempty"`
	// The proxy member UUID
	ProxyMemberUuid []byte `protobuf:"bytes,6,opt,name=proxyMemberUuid,proto3" json:"proxyMemberUuid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_proxy_service_messages_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_service_messages_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_proxy_service_messages_v1_proto_rawDescGZIP(), []int{3}
}

func (x *InitResponse) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *InitResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InitResponse) GetEncodedVersion() int32 {
	if x != nil {
		return x.EncodedVersion
	}
	return 0
}

func (x *InitResponse) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *InitResponse) GetProxyMemberId() int32 {
	if x != nil {
		return x.ProxyMemberId
	}
	return 0
}

func (x *InitResponse) GetProxyMemberUuid() []byte {
	if x != nil {
		return x.ProxyMemberUuid
	}
	return nil
}

type ClientMemberIdentity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the cluster with which this member is associated.
	ClusterName *string `protobuf:"bytes,1,opt,name=clusterName,proto3,oneof" json:"clusterName,omitempty"`
	// The Member's machine Id. This identifier should be the same for Members that are on
	// the same physical machine, and ideally different for Members that are on different
	// physical machines.
	MachineId int32 `protobuf:"varint,2,opt,name=machineId,proto3" json:"machineId,omitempty"`
	// The configured name for the Machine (such as a host name) in which this Member resides.
	// This name is used for logging purposes and to differentiate among multiple servers,
	// and may be used as the basis for determining the MachineId property.
	MachineName *string `protobuf:"bytes,3,opt,name=machineName,proto3,oneof" json:"machineName,omitempty"`
	// The configured name for the Member. This name is used for logging purposes and
	// to differentiate among Members running within a particular process.
	MemberName *string `protobuf:"bytes,4,opt,name=memberName,proto3,oneof" json:"memberName,omitempty"`
	// The member priority
	Priority int32 `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	// The configured name for the Process (such as a JVM) in which this Member resides.
	// This name is used for logging purposes and to differentiate among multiple processes on a a single machine.
	ProcessName *string `protobuf:"bytes,6,opt,name=processName,proto3,oneof" json:"processName,omitempty"`
	// The configured name for the Rack (such as a physical rack, cage or blade frame) in which
	// this Member resides. This name is used for logging purposes and to differentiate among multiple
	// racks within a particular data center, for example.
	RackName *string `protobuf:"bytes,7,opt,name=rackName,proto3,oneof" json:"rackName,omitempty"`
	// The configured name for the Site (such as a data center) in which this Member resides.
	// This name is used for logging purposes and to differentiate among multiple geographic sites.
	SiteName *string `protobuf:"bytes,8,opt,name=siteName,proto3,oneof" json:"siteName,omitempty"`
	// The configured role name for the Member. This role is completely definable by the application,
	// and can be used to determine what Members to use for specific purposes.
	RoleName      *string `protobuf:"bytes,9,opt,name=roleName,proto3,oneof" json:"roleName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMemberIdentity) Reset() {
	*x = ClientMemberIdentity{}
	mi := &file_proxy_service_messages_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMemberIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMemberIdentity) ProtoMessage() {}

func (x *ClientMemberIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_service_messages_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMemberIdentity.ProtoReflect.Descriptor instead.
func (*ClientMemberIdentity) Descriptor() ([]byte, []int) {
	return file_proxy_service_messages_v1_proto_rawDescGZIP(), []int{4}
}

func (x *ClientMemberIdentity) GetClusterName() string {
	if x != nil && x.ClusterName != nil {
		return *x.ClusterName
	}
	return ""
}

func (x *ClientMemberIdentity) GetMachineId() int32 {
	if x != nil {
		return x.MachineId
	}
	return 0
}

func (x *ClientMemberIdentity) GetMachineName() string {
	if x != nil && x.MachineName != nil {
		return *x.MachineName
	}
	return ""
}

func (x *ClientMemberIdentity) GetMemberName() string {
	if x != nil && x.MemberName != nil {
		return *x.MemberName
	}
	return ""
}

func (x *ClientMemberIdentity) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ClientMemberIdentity) GetProcessName() string {
	if x != nil && x.ProcessName != nil {
		return *x.ProcessName
	}
	return ""
}

func (x *ClientMemberIdentity) GetRackName() string {
	if x != nil && x.RackName != nil {
		return *x.RackName
	}
	return ""
}

func (x *ClientMemberIdentity) GetSiteName() string {
	if x != nil && x.SiteName != nil {
		return *x.SiteName
	}
	return ""
}

func (x *ClientMemberIdentity) GetRoleName() string {
	if x != nil && x.RoleName != nil {
		return *x.RoleName
	}
	return ""
}

var File_proxy_service_messages_v1_proto protoreflect.FileDescriptor

const file_proxy_service_messages_v1_proto_rawDesc = "" +
	"\n" +
	"\x1fproxy_service_messages_v1.proto\x12\x12coherence.proxy.v1\x1a\x18common_messages_v1.proto\x1a\x19google/protobuf/any.proto\"\xf4\x02\n" +
	"\fProxyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x125\n" +
	"\x04init\x18\x03 \x01(\v2\x1f.coherence.proxy.v1.InitRequestH\x00R\x04init\x120\n" +
	"\amessage\x18\x04 \x01(\v2\x14.google.protobuf.AnyH\x00R\amessage\x12E\n" +
	"\theartbeat\x18\x05 \x01(\v2%.coherence.common.v1.HeartbeatMessageH\x00R\theartbeat\x12G\n" +
	"\acontext\x18\x06 \x03(\v2-.coherence.proxy.v1.ProxyRequest.ContextEntryR\acontext\x1aP\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01B\t\n" +
	"\arequest\"\xf0\x03\n" +
	"\rProxyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x126\n" +
	"\x04init\x18\x04 \x01(\v2 .coherence.proxy.v1.InitResponseH\x00R\x04init\x120\n" +
	"\amessage\x18\x05 \x01(\v2\x14.google.protobuf.AnyH\x00R\amessage\x129\n" +
	"\x05error\x18\x06 \x01(\v2!.coherence.common.v1.ErrorMessageH\x00R\x05error\x12;\n" +
	"\bcomplete\x18\a \x01(\v2\x1d.coherence.common.v1.CompleteH\x00R\bcomplete\x12E\n" +
	"\theartbeat\x18\b \x01(\v2%.coherence.common.v1.HeartbeatMessageH\x00R\theartbeat\x12H\n" +
	"\acontext\x18\t \x03(\v2..coherence.proxy.v1.ProxyResponse.ContextEntryR\acontext\x1aP\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01B\n" +
	"\n" +
	"\bresponse\"\xfa\x02\n" +
	"\vInitRequest\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12(\n" +
	"\x0fprotocolVersion\x18\x05 \x01(\x05R\x0fprotocolVersion\x12:\n" +
	"\x18supportedProtocolVersion\x18\x06 \x01(\x05R\x18supportedProtocolVersion\x12!\n" +
	"\theartbeat\x18\a \x01(\x03H\x00R\theartbeat\x88\x01\x01\x12#\n" +
	"\n" +
	"clientUuid\x18\b \x01(\fH\x01R\n" +
	"clientUuid\x88\x01\x01\x12I\n" +
	"\bidentity\x18\t \x01(\v2(.coherence.proxy.v1.ClientMemberIdentityH\x02R\bidentity\x88\x01\x01B\f\n" +
	"\n" +
	"_heartbeatB\r\n" +
	"\v_clientUuidB\v\n" +
	"\t_identity\"\xde\x01\n" +
	"\fInitResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12&\n" +
	"\x0eencodedVersion\x18\x03 \x01(\x05R\x0eencodedVersion\x12(\n" +
	"\x0fprotocolVersion\x18\x04 \x01(\x05R\x0fprotocolVersion\x12$\n" +
	"\rproxyMemberId\x18\x05 \x01(\x05R\rproxyMemberId\x12(\n" +
	"\x0fproxyMemberUuid\x18\x06 \x01(\fR\x0fproxyMemberUuid\"\xb3\x03\n" +
	"\x14ClientMemberIdentity\x12%\n" +
	"\vclusterName\x18\x01 \x01(\tH\x00R\vclusterName\x88\x01\x01\x12\x1c\n" +
	"\tmachineId\x18\x02 \x01(\x05R\tmachineId\x12%\n" +
	"\vmachineName\x18\x03 \x01(\tH\x01R\vmachineName\x88\x01\x01\x12#\n" +
	"\n" +
	"memberName\x18\x04 \x01(\tH\x02R\n" +
	"memberName\x88\x01\x01\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12%\n" +
	"\vprocessName\x18\x06 \x01(\tH\x03R\vprocessName\x88\x01\x01\x12\x1f\n" +
	"\brackName\x18\a \x01(\tH\x04R\brackName\x88\x01\x01\x12\x1f\n" +
	"\bsiteName\x18\b \x01(\tH\x05R\bsiteName\x88\x01\x01\x12\x1f\n" +
	"\broleName\x18\t \x01(\tH\x06R\broleName\x88\x01\x01B\x0e\n" +
	"\f_clusterNameB\x0e\n" +
	"\f_machineNameB\r\n" +
	"\v_memberNameB\x0e\n" +
	"\f_processNameB\v\n" +
	"\t_rackNameB\v\n" +
	"\t_siteNameB\v\n" +
	"\t_roleNameB_\n" +
	"+com.oracle.coherence.grpc.messages.proxy.v1P\x01Z.github.com/oracle/coherence-go-client/proto/v1b\x06proto3"

var (
	file_proxy_service_messages_v1_proto_rawDescOnce sync.Once
	file_proxy_service_messages_v1_proto_rawDescData []byte
)

func file_proxy_service_messages_v1_proto_rawDescGZIP() []byte {
	file_proxy_service_messages_v1_proto_rawDescOnce.Do(func() {
		file_proxy_service_messages_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_service_messages_v1_proto_rawDesc), len(file_proxy_service_messages_v1_proto_rawDesc)))
	})
	return file_proxy_service_messages_v1_proto_rawDescData
}

var file_proxy_service_messages_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proxy_service_messages_v1_proto_goTypes = []any{
	(*ProxyRequest)(nil),         // 0: coherence.proxy.v1.ProxyRequest
	(*ProxyResponse)(nil),        // 1: coherence.proxy.v1.ProxyResponse
	(*InitRequest)(nil),          // 2: coherence.proxy.v1.InitRequest
	(*InitResponse)(nil),         // 3: coherence.proxy.v1.InitResponse
	(*ClientMemberIdentity)(nil), // 4: coherence.proxy.v1.ClientMemberIdentity
	nil,                          // 5: coherence.proxy.v1.ProxyRequest.ContextEntry
	nil,                          // 6: coherence.proxy.v1.ProxyResponse.ContextEntry
	(*anypb.Any)(nil),            // 7: google.protobuf.Any
	(*HeartbeatMessage)(nil),     // 8: coherence.common.v1.HeartbeatMessage
	(*ErrorMessage)(nil),         // 9: coherence.common.v1.ErrorMessage
	(*Complete)(nil),             // 10: coherence.common.v1.Complete
}
var file_proxy_service_messages_v1_proto_depIdxs = []int32{
	2,  // 0: coherence.proxy.v1.ProxyRequest.init:type_name -> coherence.proxy.v1.InitRequest
	7,  // 1: coherence.proxy.v1.ProxyRequest.message:type_name -> google.protobuf.Any
	8,  // 2: coherence.proxy.v1.ProxyRequest.heartbeat:type_name -> coherence.common.v1.HeartbeatMessage
	5,  // 3: coherence.proxy.v1.ProxyRequest.context:type_name -> coherence.proxy.v1.ProxyRequest.ContextEntry
	3,  // 4: coherence.proxy.v1.ProxyResponse.init:type_name -> coherence.proxy.v1.InitResponse
	7,  // 5: coherence.proxy.v1.ProxyResponse.message:type_name -> google.protobuf.Any
	9,  // 6: coherence.proxy.v1.ProxyResponse.error:type_name -> coherence.common.v1.ErrorMessage
	10, // 7: coherence.proxy.v1.ProxyResponse.complete:type_name -> coherence.common.v1.Complete
	8,  // 8: coherence.proxy.v1.ProxyResponse.heartbeat:type_name -> coherence.common.v1.HeartbeatMessage
	6,  // 9: coherence.proxy.v1.ProxyResponse.context:type_name -> coherence.proxy.v1.ProxyResponse.ContextEntry
	4,  // 10: coherence.proxy.v1.InitRequest.identity:type_name -> coherence.proxy.v1.ClientMemberIdentity
	7,  // 11: coherence.proxy.v1.ProxyRequest.ContextEntry.value:type_name -> google.protobuf.Any
	7,  // 12: coherence.proxy.v1.ProxyResponse.ContextEntry.value:type_name -> google.protobuf.Any
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proxy_service_messages_v1_proto_init() }
func file_proxy_service_messages_v1_proto_init() {
	if File_proxy_service_messages_v1_proto != nil {
		return
	}
	file_common_messages_v1_proto_init()
	file_proxy_service_messages_v1_proto_msgTypes[0].OneofWrappers = []any{
		(*ProxyRequest_Init)(nil),
		(*ProxyRequest_Message)(nil),
		(*ProxyRequest_Heartbeat)(nil),
	}
	file_proxy_service_messages_v1_proto_msgTypes[1].OneofWrappers = []any{
		(*ProxyResponse_Init)(nil),
		(*ProxyResponse_Message)(nil),
		(*ProxyResponse_Error)(nil),
		(*ProxyResponse_Complete)(nil),
		(*ProxyResponse_Heartbeat)(nil),
	}
	file_proxy_service_messages_v1_proto_msgTypes[2].OneofWrappers = []any{}
	file_proxy_service_messages_v1_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_service_messages_v1_proto_rawDesc), len(file_proxy_service_messages_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_service_messages_v1_proto_goTypes,
		DependencyIndexes: file_proxy_service_messages_v1_proto_depIdxs,
		MessageInfos:      file_proxy_service_messages_v1_proto_msgTypes,
	}.Build()
	File_proxy_service_messages_v1_proto = out.File
	file_proxy_service_messages_v1_proto_goTypes = nil
	file_proxy_service_messages_v1_proto_depIdxs = nil
}
