//
// Copyright (c) 2020, 2024, Oracle and/or its affiliates.
//
// Licensed under the Universal Permissive License v 1.0 as shown at
// https://oss.oracle.com/licenses/upl.

// NamedCacheService V2 service definition.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.2
// source: proxy_service_v1.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proxy_service_v1_proto protoreflect.FileDescriptor

const file_proxy_service_v1_proto_rawDesc = "" +
	"\n" +
	"\x16proxy_service_v1.proto\x12\x12coherence.proxy.v1\x1a\x1fproxy_service_messages_v1.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto2g\n" +
	"\fProxyService\x12W\n" +
	"\n" +
	"subChannel\x12 .coherence.proxy.v1.ProxyRequest\x1a!.coherence.proxy.v1.ProxyResponse\"\x00(\x010\x01B_\n" +
	"+com.oracle.coherence.grpc.services.proxy.v1P\x01Z.github.com/oracle/coherence-go-client/proto/v1b\x06proto3"

var file_proxy_service_v1_proto_goTypes = []any{
	(*ProxyRequest)(nil),  // 0: coherence.proxy.v1.ProxyRequest
	(*ProxyResponse)(nil), // 1: coherence.proxy.v1.ProxyResponse
}
var file_proxy_service_v1_proto_depIdxs = []int32{
	0, // 0: coherence.proxy.v1.ProxyService.subChannel:input_type -> coherence.proxy.v1.ProxyRequest
	1, // 1: coherence.proxy.v1.ProxyService.subChannel:output_type -> coherence.proxy.v1.ProxyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proxy_service_v1_proto_init() }
func file_proxy_service_v1_proto_init() {
	if File_proxy_service_v1_proto != nil {
		return
	}
	file_proxy_service_messages_v1_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_service_v1_proto_rawDesc), len(file_proxy_service_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proxy_service_v1_proto_goTypes,
		DependencyIndexes: file_proxy_service_v1_proto_depIdxs,
	}.Build()
	File_proxy_service_v1_proto = out.File
	file_proxy_service_v1_proto_goTypes = nil
	file_proxy_service_v1_proto_depIdxs = nil
}
