# Copyright 2025 Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.

# ---------------------------------------------------------------------------
# Coherence Go Client GitHub Actions - Kind Tests
# ---------------------------------------------------------------------------
name: CI Kind Tests

on:
  push:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      go-version:
        description: "Go version (comma-separated for matrix)"
        required: false
        default: "1.23.x,1.24.x"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - 1.23.x
          - 1.24.x

#   Checkout the source, we need a depth of zero to fetch all of the history otherwise
#   the copyright check cannot work out the date of the files from Git.
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Cache Go Modules
      if: github.event_name == 'workflow_dispatch'
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-mods-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mods-

    - name: Set up Go
      if: github.event_name == 'workflow_dispatch'
      uses: actions/setup-go@v5
      with:
        go-version: '${{ matrix.go-version }}'

    - name: Create Kind Cluster
      if: github.event_name == 'workflow_dispatch'
      shell: bash
      run: |
        make kind
        make create-namespace deploy-operator
        make deploy-coherence

    - name: Run Tests
      if: github.event_name == 'workflow_dispatch'
      shell: bash
      run: |
        kubectl get pods -n coherence-perf

    - name: Shutdown
      if: github.event_name == 'workflow_dispatch'
      shell: bash
      run: |
        make kind-stop

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-output-${{ matrix.go-version }}-${{ matrix.coherenceVersion }}
        path: build/_output/test-logs

    - uses: actions/upload-artifact@v4
      with:
        name: test-result-${{ matrix.go-version }}-${{ matrix.coherenceVersion }}
        path:  test/e2e/perf/results.txt
