# Copyright 2022, 2025 Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.

# ---------------------------------------------------------------------------
# Coherence Go Client GitHub Actions CI build.
# ---------------------------------------------------------------------------
name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    timeout-minutes: 60
    strategy:
      matrix:
        go-version:
          - 1.23.x
          - 1.24.x

#   Checkout the source, we need a depth of zero to fetch all of the history otherwise
#   the copyright check cannot work out the date of the files from Git.
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Cache Go Modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-mods-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mods-

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '${{ matrix.go-version }}'

    - name: Get Docker Images
      shell: bash
      run: |
        docker pull gcr.io/distroless/java17-debian12
        docker pull gcr.io/distroless/java11-debian11

    - name: E2E Local Tests
      shell: bash
      run: |
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1
        INCLUDE_LONG_RUNNING=true PROFILES=,-jakarta,javax COHERENCE_VERSION=22.06.13 make clean generate-proto build-test-images test-e2e-standalone

    - name: Profile Near Cache
      shell: bash
      run: |
        make profile-near-cache

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-output-${{ matrix.go-version }}
        path: build/_output/test-logs

    - name: E2E Local Tests With Scope
      shell: bash
      run: |
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1
        SKIP_PROTO_GENERATION=true COHERENCE_VERSION=22.06.13 PROFILES=,-jakarta,javax,scope make clean generate-proto build-test-images test-e2e-standalone-scope

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-output-${{ matrix.go-version }}
        path: build/_output/test-logs

    - name: E2E Local Tests SSL (env)
      shell: bash
      run: |
        SKIP_PROTO_GENERATION=true SECURE=env COHERENCE_IGNORE_INVALID_CERTS=true \
          COHERENCE_TLS_CERTS_PATH=`pwd`/test/utils/certs/guardians-ca.crt \
          COHERENCE_TLS_CLIENT_CERT=`pwd`/test/utils/certs/star-lord.crt \
          COHERENCE_TLS_CLIENT_KEY=`pwd`/test/utils/certs/star-lord.key \
          COHERENCE_VERSION=22.06.13 PROFILES=,secure,-jakarta,javax make clean certs generate-proto build-test-images test-e2e-standalone

    - name: E2E Local Tests SSL (options)
      shell: bash
      run: |
        SKIP_PROTO_GENERATION=true SECURE=options COHERENCE_IGNORE_INVALID_CERTS_OPTION=true \
          COHERENCE_TLS_CERTS_PATH_OPTION=`pwd`/test/utils/certs/guardians-ca.crt \
          COHERENCE_TLS_CLIENT_CERT_OPTION=`pwd`/test/utils/certs/star-lord.crt \
          COHERENCE_TLS_CLIENT_KEY_OPTION=`pwd`/test/utils/certs/star-lord.key \
          COHERENCE_VERSION=22.06.13 PROFILES=,secure,-jakarta,javax,scope make clean certs generate-proto build-test-images test-e2e-standalone-scope

    - name: E2E Local Tests SSL (tlsConfig)
      shell: bash
      run: |
        SKIP_PROTO_GENERATION=true SECURE=tlsConfig COHERENCE_IGNORE_INVALID_CERTS_OPTION=true \
          COHERENCE_TLS_CERTS_PATH_OPTION=`pwd`/test/utils/certs/guardians-ca.crt \
          COHERENCE_TLS_CLIENT_CERT_OPTION=`pwd`/test/utils/certs/star-lord.crt \
          COHERENCE_TLS_CLIENT_KEY_OPTION=`pwd`/test/utils/certs/star-lord.key \
          COHERENCE_VERSION=22.06.13 PROFILES=,secure,-jakarta,javax,scope make clean certs generate-proto build-test-images test-e2e-standalone-scope

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-output-${{ matrix.go-version }}
        path: build/_output/test-logs
