# Copyright 2022, 2025 Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.

# ---------------------------------------------------------------------------
# Coherence Go Client GitHub Actions test examples against v22.06 versions
# and v1.2.2 client
# ---------------------------------------------------------------------------
name: CI-Examples v22.06 - v1.2.2

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        coherenceVersion:
          - 22.06.12-SNAPSHOT
          - 22.06.10
          - 22.06.11
        go-version:
          - 1.19.x
          - 1.20.x
          - 1.21.x
          - 1.22.x
          - 1.23.x

#   Checkout the source, we need a depth of zero to fetch all of the history otherwise
#   the copyright check cannot work out the date of the files from Git.
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get Docker Images
      shell: bash
      run: |
        docker pull gcr.io/distroless/java11-debian11
        uname -a

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'zulu'

    - name: Cache Go Modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-mods-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mods-

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '${{ matrix.go-version }}'

    - name: Verify Examples
      shell: bash
      run: |
        git checkout v1.2.2
        # Change the jib-maven-plugin as this version fails
        sed -i.bak 's/<version.plugin.jib>3\.3\.0<\/version.plugin.jib>/<version.plugin.jib>3.4.3<\/version.plugin.jib>/' java/pom.xml
        go get google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0
        COHERENCE_BASE_IMAGE=gcr.io/distroless/java11-debian11 COHERENCE_VERSION=${{ matrix.coherenceVersion }} PROFILES=,-jakarta,javax make clean generate-proto build-test-images test-cluster-startup test-examples
        make test-cluster-shutdown || true

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-output-${{ matrix.go-version }}-${{ matrix.coherenceVersion }}
        path: build/_output/test-logs
