# Copyright 2022, 2025 Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.

# ---------------------------------------------------------------------------
# Coherence Resolver Compatability Tests
# ---------------------------------------------------------------------------
name: Resolver Compatability

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        coherenceVersion:
          - 22.06.11
          - 24.09.3
          - 14.1.2-0-1
        go-version:
          - 1.23.x
          - 1.24.x

#   Checkout the source, we need a depth of zero to fetch all of the history otherwise
#   the copyright check cannot work out the date of the files from Git.
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Cache Go Modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-mods-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mods-

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '${{ matrix.go-version }}'

    - name: Discovery Compatability Tests
      shell: bash
      run: |
        export COHERENCE_VERSION=${{ matrix.coherenceVersion }}
        curl -sL https://raw.githubusercontent.com/oracle/coherence-cli/main/scripts/install.sh | bash
        cohctl version
        cohctl create cluster grpc-cluster -v ${{ matrix.coherenceVersion }} -y -a coherence-grpc-proxy 
        sleep 20
        cohctl monitor health -n localhost:7574 -T 40 -w
        make clean test-clean test-resolver

    - name: Examples Tests Using Resolver
      shell: bash
      run: |
        export COHERENCE_SERVER_ADDRESS=coherence:///localhost:7574
        ./scripts/run-test-examples.sh
        cohctl stop cluster grpc-cluster -y
        cohctl remove cluster grpc-cluster -y

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-output-${{ matrix.go-version }}-${{ matrix.coherenceVersion }}
        path: build/_output/test-logs
